const products = [
  {
    _id: '1',
    name: ' The Shore - Sea view pool villa - no ebo ',
    image: '/images/shore',
    description: 'high season Nov 1 - Dec 20',
    brand: 'The Shore Katathanii',
    category: '5-star pool Villa',
    city: 'phuket',
    price: 17195,
    countInStock: 100,
  },
  {
    _id: '2',
    name: ' The Shore - Sea view pool villa - no ebo ',
    image: '/images/shore',
    description: 'Peak Season season Dec 20 - Jan 20',
    brand: 'The Shore Katathanii',
    category: '5-star pool Villa',
    city: 'phuket',
    price: 28000,
    countInStock: 100,
  },
  {
    _id: '3',
    name: ' The Shore - Sea view pool villa - no ebo ',
    image: '/images/shore',
    description: 'Low Season season Dec 20 - Jan 20',
    brand: 'The Shore Katathanii',
    category: '5-star pool Villa',
    city: 'phuket',
    price: 28000,
    countInStock: 100,
  },
  {
    _id: '4',
    name: ' The Shore - pool villa - no ebo ',
    image: '/images/shore',
    description: 'high season Nov 1 - Dec 20',
    brand: 'The Shore Katathanii',
    category: '5-star pool Villa',
    city: 'phuket',
    price: 13195,
    countInStock: 100,
  },
  {
    _id: '5',
    name: ' The Shore - pool villa - no ebo ',
    image: '/images/shore',
    description: 'Peak Season season Dec 20 - Jan 20',
    brand: 'The Shore Katathanii',
    category: '5-star pool Villa',
    city: 'phuket',
    price: 21000,
    countInStock: 100,
  },
  {
    _id: '6',
    name: ' The Shore -  pool villa - no ebo ',
    image: '/images/shore',
    description: 'Low Season season Dec 20 - Jan 20',
    brand: 'The Shore Katathanii',
    category: '5-star pool Villa',
    price: 11000,
    countInStock: 100,
  },
]

export default products
